### ISSUE TITLE
Ajuda?

### ISSUE THREAD

**Issue by tloriato** [dfalbel/captchaReceita2#1]
Você pode ajudar um iniciante a rodar o projeto?

Nunca usei R na vida, apesar de achar bem interessante...

Estou prestando atenção ao projeto para tentar integrar ele ao meu código em Node.js mas não queria dar trabalho perguntando tudo, então só como rodar já ajudaria heheh

Ubuntu 16.04
_(Ou Ruindows 10)_

**Comment by dfalbel** [comment]
Esse projeto é um pouco complicado para rodar sem nunca ter feito nada em R. Tenta usar esse aqui: 

https://github.com/jtrecenti/cnpjReceita

Ou esse daqui:

https://github.com/decryptr/captchaReceitaAudio

Que estão mais organizados!!

**Comment by murilogibim** [comment]
@dfalbel você acha que aumentando a quantidade de captchas resolvidos na biblioteca aumentariamos a assertividade? tenho cerca de 1300 captchas resolvidos que gostaria de incluir na biblioteca. 

o algoritimo está reconhecendo muito bem, porém normalmente acerta 4/5 das 6 letras.

além disso, ótimo trabalho :+1:

**Comment by dfalbel** [comment]
Com certeza deve melhorar! @murilogibim você já olhou este projeto? https://github.com/decryptr/captchaReceitaAudio ele quebra usando o áudio e fica determinístico.

Neste outro https://github.com/decryptr/captchaReceitaData/tree/master/inst/img guardamos os dados... Seria legal fazer um Pull Request lá. 

Se estiver consultando CNPJ na receita federal, o @jtrecenti encapsulou tudo em um pacote só: https://github.com/jtrecenti/cnpjReceita

**Comment by murilogibim** [comment]
@dfalbel achei interessante a parte do áudio, mas achei que não estava disponível (pelo menos não consigo ouvir como usuário final). 

Na empresa em que trabalho estamos utilizando para a consulta do CT-e (http://www.cte.fazenda.gov.br/portal/consulta.aspx?tipoConsulta=completa&tipoConteudo=mCK/KoCqru0=) o captcha é o mesmo, mas o audio parece estar off. Vou fazer um pull request neste repositorio que mandou a noite.

**Comment by murilogibim** [comment]
Ué... parece que o som voltou... não sei se fico feliz ou triste, pois não consigo determinar o up-time deste aúdio... enfim, vou testar este repo que mandou e a noite mando os captchas via pr. Valeu :)

**Comment by dfalbel** [comment]
@murilogibim quando fizer o PR tento melhorar o modelo de previsão da img tbm!

**Comment by jtrecenti** [comment]
Legal! Acho bacana a gente centralizar coisas de captchas na página decryptr, o que acham?
