### ISSUE TITLE
Erro ao usar separar(bd)

### ISSUE THREAD

**Issue by lucascnr** [dfalbel/captchaReceita2#2]
O erro é o seguinte:

Error in eval(expr, envir, enclos) : objeto 'arqs' não encontrado

**Comment by dfalbel** [comment]
consegue colocar o resultado de `head(bd)` para eu ver porque isso acontece?

**Comment by lucascnr** [comment]
```
> head(bd)
[1] corte   posicao letras 
<0 linhas> (ou row.names de comprimento 0)
```

Por algum motivo pensei que essa lista seria preenchida...

Como então eu iria criar essa base? Devo salvar as saídas de
```
a %>% captchaReceita:::processar() %>% desenhar()
```

em uma pasta e depois rodar

```
bd <- preparar(dir = "data-raw/")
```

Seria isso?

**Comment by lucascnr** [comment]
Foi um erro da minha parte, pensei que eu deveria criar o diretório ```data-raw```, mas ele ja existe na raiz do projeto.

Obrigado por responder

**Comment by dfalbel** [comment]
Boa! Que bom que deu certo! Recentemente o @murilogibim adicionou mais imagens aqui: https://github.com/decryptr/captchaReceitaData/tree/master/inst/img Vc pode usá-las se quiser treinar o seu algorítmo.

**Comment by lucascnr** [comment]
Nossa muito bom! Já estou fazendo algo do tipo, quando eu finalizar minha base de imagens posso compartilhar com vc tbm.

Mas tenho uma dúvida, eu vi que extensão dos arquivos na pasta ```data-raw``` são .rds, eu devo fazer alguma conversão de .png para .rds?

**Comment by dfalbel** [comment]
Cada arquivo no `data-raw` é o resultado de: 

```
b <- download() %>% ler()
saveRDS(b, "captcha.rds")
```

Mas é sempre bom guardar a imagem (.png) em  algum lugar.

**Comment by lucascnr** [comment]
Ao fazer:

``` saveRDS(b, "captcha.rds") ```

devo indicar a resposta no nome do arquivo? 

Por exemplo: Xa1mns.rds.

**Comment by dfalbel** [comment]
isso!

**Comment by lucascnr** [comment]
Muito obrigado @dfalbel!
